export const LOGIN="LOGIN";
export const SWITCH_INACTIVE="SWITCH_INACTIVE"
export const SWITCH_ACTIVE="SWITCH_ACTIVE"
export const LOGIN_ERROR='LOGIN_ERROR'
export const FORGET_PASSWORD='FORGET_PASSWORD'
export const PASSWORD_ERROR='PASSWORD_ERROR'
export const SIGN_UP='SIGN_UP'
export const SINGNUP_ERROR='SINGNUP_ERROR'
export const GOOGLE_LOGIN='GOOGLE_LOGIN'
export const GOOGLE_ERROR='GOOGLE_ERROR'
export const NEW_PASSWORD='NEW_PASSWORD'



